[package]
name = "logisheets"
version = "0.3.0"
description = "A web spreadsheets application written in Rust and Typescript"
keywords = ["excel", "spreadsheets", "ooxml", "logisheets"]
readme = "README.md"
repository = "https://github.com/proclml/LogiSheets"
license = "MIT"
include = [
    "crates/workbook/**/*",
    "crates/controller/**/*",
    "src/lib.rs",
    "Cargo.toml",
]

[workspace]
members = [
    "crates/*",
    "src/wasms/fc",
    "src/wasms/server",
]

[dependencies]
logisheets_controller = {path = "crates/controller", version = "0.3.0"}
logisheets_workbook = {path = "crates/workbook", version = "0.3.0"}
