[package]
name = "logisheets"
version = "0.1.0"

[workspace]
members = [
    "crates/*",
    "src/wasms/fc",
    "src/wasms/server",
]

[dependencies]
logisheets_controller = {path = "crates/controller", version = "0.1.0"}
logisheets_workbook = {path = "crates/workbook", version = "0.1.0"}
