[package]
name = "controller_base"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
futures = "0.3.19"
im = "15.0.0"
serde = {version = "1.0.125", features = ["derive"]}
logisheets_workbook = {version = "0.1.0", path = "../../workbook"}
