[package]
name = "parser"
version = "0.1.1"
edition = "2018"

[dependencies]
lexer = {version = "0.1.0", path = "../lexer"}
lazy_static = "1.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"
chrono = "0.4.19"
indexmap = { version = "1.6.1" }
controller_base = {version = "0.1.0", path = "../base"}
regex = "1"
