[package]
authors = ["Jiangming He"]
edition = "2018"
name = "logisheets_workbook"
version = "0.1.0"

[dependencies]
convert_case = "0.4.0"
linked-hash-map = {version = "0.5.3", features = ["serde_impl"]}
paste = "1.0.5"
quick-xml = {version = "0.22.0", features = ["serialize"]}
regex = "1"
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.59"
serde_repr = "0.1"
thiserror = "1.0.24"
zip = {version = "0.6.0", default-features = false, features = ["deflate"]}
xmlserde = {path = "./xmlserde", version = "0.1.0"}
derives = {path = "./derives", version = "0.1.0"}

