[package]
authors = ["ImJeremyHe<yiliang.he@qq.com>"]
edition = "2018"
name = "logisheets_workbook"
version = "0.3.0"
license = "MIT"
description = "Tools for LogiSheets to unarchive and write .xlsx file"

[dependencies]
xmlserde = {version = "0.3.0", path = "../xmlserde"}
logisheets_workbook_derives = {version = "0.3.0", path = "./derives"}
zip = {version = "0.6.0", default-features = false, features = ["deflate"]}
ts-rs = "6.1.2"
thiserror = "1.0.24"
quick-xml = {version = "0.22.0", features = ["serialize"]}
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.59"
regex = "1"