[package]
name = "logisheets_xmlserde"
edition = "2018"
version = "0.2.1"
description = "read and write the ooxml files"
authors = ["ImJeremyHe<yiliang.he@qq.com>"]
license = "MIT"

[dependencies]
paste = "1.0.5"
quick-xml = {version = "0.22.0", features = ["serialize"]}
regex = "1"
serde = {version = "1.0.125", features = ["derive"]}
logisheets_derives = {path = "../derives", version = "0.2.1"}
ts-rs = "6.1.2"

[dev-dependencies]
serde_json = "1.0.59"