[package]
authors = ["Jiangming He"]
edition = "2018"
name = "logisheets_xmlserde"
version = "0.1.0"

[dependencies]
logisheets_derives = {path = "../derives"}
paste = "1.0.5"
quick-xml = {version = "0.22.0", features = ["serialize"]}
regex = "1"
serde = {version = "1.0.125", features = ["derive"]}
